### ISSUE TITLE
Food supply Quorum tutorial error "authentication needed: password or unlock"

### ISSUE THREAD

**Issue by akegaviar** [chainstack/docs#100]
@ThomasRalee while working updating the docs to reflect the protected Quorum APIs, I tested the [Quorum food supply tutorial](https://docs.dev.chainstack.com/tutorials/food-supply-temperature-control-on-quorum) and it's not deploying anymore.

Note that I specify the `.env` in the following format (just in case, I don't think this is the issue):

```
RPC1='https://user-name:pass-word-pass-word-pass-word@nd-123-456-789.int.chainstack.com'
PK1='TRANSACTION_MANAGER_PUBLIC_KEY'
RPC2='https://user-name:-pass-word-pass-word-pass-word@nd-123-456-789.int.chainstack.com'
PK2='TRANSACTION_MANAGER_PUBLIC_KEY'
RPC3='https://user-name:pass-word-pass-word-pass-word@nd-123-456-789.int.chainstack.com'
PK3='TRANSACTION_MANAGER_PUBLIC_KEY'
```

Whenever I run `node public.js` it's failing with:

```
(node:8646) UnhandledPromiseRejectionWarning: Error: Returned error: authentication needed: password or unlock
    at Object.ErrorResponse (/root/fuck/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /root/fuck/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/root/fuck/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/root/fuck/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/root/fuck/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/root/fuck/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/root/fuck/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:8646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8646) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Returned error: authentication needed: password or unlock
    at Object.ErrorResponse (/root/fuck/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /root/fuck/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/root/fuck/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/root/fuck/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/root/fuck/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/root/fuck/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/root/fuck/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

This probably has to do with [web3 version 1.2.1](https://www.npmjs.com/package/web3).

I'm assigning this issue to you for the time being. Please let me know how this can be fixed and I'll update the tutorial.

**Comment by akegaviar** [comment]
On prod with the Quorum nodes not protected, `public.js` deploys the contract but also gives the error:

```
(node:8736) UnhandledPromiseRejectionWarning: Error: Please use the "new" keyword to instantiate a web3.eth.contract() object!
    at Eth.Contract (/root/fuck/node_modules/web3-eth-contract/src/index.js:59:15)
    at Eth.Contract (/root/fuck/node_modules/web3-eth/src/index.js:149:22)
    at getContract (/root/fuck/public.js:50:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async setTemperature (/root/fuck/public.js:82:22)
    at async main (/root/fuck/public.js:40:18)
(node:8736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
``

**Comment by syahrul12345** [comment]
@akegaviar 
On protected Quorum nodes you have to unlock the node account first:
`await web3.eth.personal.unlockAccount(address,'',1000)`
so like this:
```
async function deployContract(web3) {
  const address = await getAddress(web3);
  await web3.eth.personal.unlockAccount(address,'',1000) //see here, this is the new line
  const contract = new web3.eth.Contract(temperatureMonitor.interface);

  return contract.deploy({
    data: temperatureMonitor.bytecode,
  })
  .send({
      from: address,
      gas: '0x2CD29C0',
  })
  .on('transactionHash',console.log)
  .on('error', console.error)
  .then((newContractInstance) => {
    return newContractInstance.options.address;
  });
}
```
Next, the tutorial is missing the `new` keyword on line 50

```
async function getContract(web3, contractAddress) {
  const address = await getAddress(web3);
  //see below
  return new web3.eth.Contract(temperatureMonitor.interface, contractAddress, {
    defaultAccount: address,
  });
}
```

I tried this and it doesn't throw the authentication or `new keyword` errors anymore. However, the 2.25 Quorum nodes seem to be very slow and the transaction isn't propogating.

**Comment by easeev** [comment]
We plan to remove `personal` API namespace from all Quorum nodes by default since it's generally not safe to manage accounts on a node hosted in the cloud. Does this change have any implications on this (or any other) tutorial?

**Comment by syahrul12345** [comment]
@easeev For this tutorial yes. `public.js` and `private.js` is using `web3.eth.send()` which requires an unlocked account. 

@akegaviar 
Without an unlocked account, we will need to build the transaction payload in the javascript file and then sign it with the private key. If we want to use the node account to deploy the contracts, then you need to supply the node private key. Otherwise any privatekey will do fine. Then we send a transaction via `web.eth.sendSignedTransaction(txPayload)`

For our other tutorials that use `truffle` or `embark` , there isn't a need to change anything. Truffle & Embark requires you to supply private keys by default , and it uses `web.eth.sendSignedTransaction(txPayload)` underneath.

**Comment by easeev** [comment]
@syahrul12345 please rework this tutorial so that it doesn't require any accounts on the node.

https://web3py.readthedocs.io/en/stable/web3.eth.account.html, we provide Hosted Nodes

**Comment by syahrul12345** [comment]
@easeev , sure i'll do a PR once it's done.

**Comment by akegaviar** [comment]
So guys I think we need to have this issue open for 1.3 release with authenticated nodes.

If we are not going to fix this tutorial by 1.3 release, we'll have to pull this down from the docs. (and reintroduce when we have a working tutorial)

**Comment by akegaviar** [comment]
Like I said, `private.js` doesn't work for protected Quorum nodes.

Error:

```
node:26678) UnhandledPromiseRejectionWarning: Error: Returned error: Non-200 status code: &{Status:500 Internal Server Error StatusCode:500 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Date:[Tue, 03 Sep 2019 10:25:55 GMT] Server:[Warp/3.2.13]] Body:0xc019615d40 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc018d77100 TLS:<nil>}
    at Object.ErrorResponse (/root/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /root/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/root/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/root/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/root/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/root/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/root/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by akegaviar** [comment]
@syahrul12345 I tested this multiple times in different configurations and it only works on Quorum Raft. It doesn't work on IBFT. I submitted a PR on this — there's no change in the code, just a note that the network must be Raft.

**Comment by easeev** [comment]
@syahrul12345 @ThomasRalee any particular reason it works only on Raft networks?
@akegaviar does it work with authenticated nodes in the end?

**Comment by syahrul12345** [comment]
@easeev there shouldn't be any difference. i'll investigate

**Comment by akegaviar** [comment]
> @akegaviar does it work with authenticated nodes in the end?

Yes, it works with authenticated nodes. I was wrong in assuming authentication was the issue.

**Comment by syahrul12345** [comment]
@akegaviar does `public.js` work for IBFT?

I thought it was a web3 issue so i did it purely with RPC calls but the same problem occured. Looks like in raft, the transactions are propagating, but in IBFT the transactions are getting stuck in the node. This is the case for `public` and `private` transactions. I will update everybody.

**Comment by akegaviar** [comment]
@syahrul12345 correct. Neither `public` not `private` work on IBFT. Both work on Raft.
